// <auto-generated />
using System;
using Agrovent.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agrovent.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251222143456_RevertToAvaArticleModel")]
    partial class RevertToAvaArticleModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.AssemblyStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssemblyVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentStructureId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyVersionId");

                    b.HasIndex("ComponentVersionId");

                    b.HasIndex("ParentStructureId");

                    b.ToTable("AssemblyStructures");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.AvaArticleModel", b =>
                {
                    b.Property<int>("Article")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Article"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Count")
                        .HasColumnType("numeric");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Article");

                    b.ToTable("AvaArticles");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId");

                    b.ToTable("ComponentFiles");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseMaterial")
                        .HasColumnType("text");

                    b.Property<decimal>("BaseMaterialCount")
                        .HasColumnType("numeric");

                    b.Property<int>("ComponentVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Paint")
                        .HasColumnType("text");

                    b.Property<decimal?>("PaintCount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId")
                        .IsUnique();

                    b.ToTable("ComponentMaterials");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId");

                    b.ToTable("ComponentProperties");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvaArticleArticle")
                        .HasColumnType("integer");

                    b.Property<int>("AvaType")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HashSum")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvaArticleArticle");

                    b.HasIndex("HashSum")
                        .IsUnique();

                    b.HasIndex("ComponentId", "Version")
                        .IsUnique();

                    b.ToTable("ComponentVersions");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.TechnologicalProcess.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LaborIntensityMinutes")
                        .HasColumnType("numeric")
                        .HasColumnName("labor_intensity_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("section");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<int>("TechnologicalProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("technological_process_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TechnologicalProcessId");

                    b.HasIndex("TechnologicalProcessId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("operations");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.TechnologicalProcess.TechnologicalProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("part_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartNumber")
                        .IsUnique();

                    b.ToTable("technological_processes");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.AssemblyStructure", b =>
                {
                    b.HasOne("Agrovent.DAL.Entities.Components.ComponentVersion", "AssemblyVersion")
                        .WithMany()
                        .HasForeignKey("AssemblyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agrovent.DAL.Entities.Components.ComponentVersion", "ComponentVersion")
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agrovent.DAL.Entities.Components.AssemblyStructure", "ParentStructure")
                        .WithMany("ChildStructures")
                        .HasForeignKey("ParentStructureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssemblyVersion");

                    b.Navigation("ComponentVersion");

                    b.Navigation("ParentStructure");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentFile", b =>
                {
                    b.HasOne("Agrovent.DAL.Entities.Components.ComponentVersion", "ComponentVersion")
                        .WithMany("Files")
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentMaterial", b =>
                {
                    b.HasOne("Agrovent.DAL.Entities.Components.ComponentVersion", "ComponentVersion")
                        .WithOne("Material")
                        .HasForeignKey("Agrovent.DAL.Entities.Components.ComponentMaterial", "ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentProperty", b =>
                {
                    b.HasOne("Agrovent.DAL.Entities.Components.ComponentVersion", "ComponentVersion")
                        .WithMany("Properties")
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentVersion", b =>
                {
                    b.HasOne("Agrovent.DAL.Entities.Components.AvaArticleModel", "AvaArticle")
                        .WithMany()
                        .HasForeignKey("AvaArticleArticle")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Agrovent.DAL.Entities.Components.Component", "Component")
                        .WithMany("Versions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaArticle");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.TechnologicalProcess.Operation", b =>
                {
                    b.HasOne("Agrovent.DAL.Entities.TechnologicalProcess.TechnologicalProcess", "TechnologicalProcess")
                        .WithMany("Operations")
                        .HasForeignKey("TechnologicalProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnologicalProcess");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.TechnologicalProcess.TechnologicalProcess", b =>
                {
                    b.HasOne("Agrovent.DAL.Entities.Components.Component", "Component")
                        .WithMany()
                        .HasForeignKey("PartNumber")
                        .HasPrincipalKey("PartNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.AssemblyStructure", b =>
                {
                    b.Navigation("ChildStructures");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.Component", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.Components.ComponentVersion", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Material");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Agrovent.DAL.Entities.TechnologicalProcess.TechnologicalProcess", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
